### ISSUE TITLE
Linux copy to clipboard

### ISSUE THREAD

**Issue by caputchinefrobles** [griegler/configs#1]
Hi. Nice configs for tmux. 

I'm having some issues with copy to clipboard on linux. Do you know if I need to install or do anything else besides installing xclip in order to copy from tmux to clipboard? I'm using kde plasma 5.13.

Thanks in advance.

**Comment by griegler** [comment]
Just changed the config a bit and it should now work fine on Linux. I deactivated it on Mac, as I do not really need it there and it would require to install something (see comment in config).

**Comment by caputchinefrobles** [comment]
Fixed perfectly. Thanks.
